# -*- coding: utf-8 -*-
"""Day3_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OC_wfX9JNMbdo1Pck8mnnSQsyyXGFZP
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

ads_data=pd.read_csv('/content/Social_Network_Ads.csv')
ads_data.head()

ads_data.columns

ads_data['User ID'].unique()

#Dropping User ID as all its values are unique
ads_data.drop('User ID',axis=1,inplace=True)

ads_data.columns

#Checking Null Value
ads_data.isna().sum()

ads_data.dtypes

ads_data['Gender'].unique()

#One hot encoding gender column
ads_data=pd.get_dummies(ads_data,prefix='Gender',dtype=int)
ads_data.head()

ads_data['Purchased'].unique()

ads_data['Purchased'].value_counts(normalize=True)
#Since no of 0s and 1s arenot same we call this as imbalanced data

#Cheking outlier
plt.boxplot(ads_data['Age'])

plt.boxplot(ads_data['EstimatedSalary'])

#Target Splitting
y=ads_data['Purchased']
x=ads_data.drop('Purchased',axis=1)

#Train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Logistic Regression Model
from sklearn.linear_model import LogisticRegression

lr_model=LogisticRegression(max_iter=1000)
lr_model.fit(x_train,y_train)
y_pred_lr_model=lr_model.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,f1_score,precision_score
print(accuracy_score(y_test,y_pred_lr_model))
print(confusion_matrix(y_test,y_pred_lr_model))
print(recall_score(y_test,y_pred_lr_model))
print(f1_score(y_test,y_pred_lr_model))
print(precision_score(y_test,y_pred_lr_model))

"""KNN"""

#KNN
#finding the optimum k value

from sklearn.neighbors import KNeighborsClassifier
acc_score=[]
for k in range(3,10):
  knn=KNeighborsClassifier(n_neighbors=k)
  knn.fit(x_train,y_train)
  y_pred_knn=knn.predict(x_test)
  acc=accuracy_score(y_test,y_pred_knn)
  acc_score.append(acc)

acc_score

plt.plot(np.arange(3,10),acc_score,'o-')
plt.grid()

#optimum k value is 5 ( ACC HIGHEST)
#Train KNN model for k=5
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred_knn=knn.predict(x_test)
print(confusion_matrix(y_test,y_pred_knn))
print(accuracy_score(y_test,y_pred_knn))
print(recall_score(y_test,y_pred_knn))
print(f1_score(y_test,y_pred_knn))
print(precision_score(y_test,y_pred_knn))

x.describe()

#Do scaling on numerical value
x_scaled_data=x.copy()

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
for i in ['Age','EstimatedSalary']:
  x_scaled_data[i]=scaler.fit_transform(x_scaled_data[[i]])

x.describe()

#train test split for scaled data
x_train_scaled,x_test_scaled,y_train_scaled,y_test_scaled=train_test_split(x_scaled_data,y,test_size=0.2,random_state=42)

#Logistic Regression model with scaled data
lr_model_scaled=LogisticRegression(max_iter=1000)
lr_model_scaled.fit(x_train_scaled,y_train_scaled)
y_pred_lr_model_scaled=lr_model_scaled.predict(x_test_scaled)

print(accuracy_score(y_test_scaled,y_pred_lr_model_scaled))
print(confusion_matrix(y_test_scaled,y_pred_lr_model_scaled))
print(recall_score(y_test_scaled,y_pred_lr_model_scaled))
print(f1_score(y_test_scaled,y_pred_lr_model_scaled))
print(precision_score(y_test_scaled,y_pred_lr_model_scaled))

#KNN
#finding the optimum k value fopr scaled

acc_score=[]
for k in range(3,10):
  knn_scaled=KNeighborsClassifier(n_neighbors=k)
  knn_scaled.fit(x_train_scaled,y_train_scaled)
  y_pred_knn_scaled=knn_scaled.predict(x_test_scaled)
  acc=accuracy_score(y_test_scaled,y_pred_knn_scaled)
  acc_score.append(acc)

acc_score

plt.plot(np.arange(3,10),acc_score,'o-')
plt.grid()

#optimum k value is 6 ( ACC HIGHEST)
#Train KNN model for k=6
knn=KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train_scaled,y_train_scaled)
y_pred_knn_scaled=knn.predict(x_test_scaled)
print(confusion_matrix(y_test_scaled,y_pred_knn_scaled))
print(accuracy_score(y_test_scaled,y_pred_knn_scaled))
print(recall_score(y_test_scaled,y_pred_knn_scaled))
print(f1_score(y_test_scaled,y_pred_knn_scaled))
print(precision_score(y_test_scaled,y_pred_knn_scaled))

#SVM
from sklearn.svm import SVC

#linear
svmclf_linear=SVC(kernel='linear')
svmclf_linear.fit(x_train,y_train)
y_pred_svmclf_linear=svmclf_linear.predict(x_test)
print(confusion_matrix(y_test,y_pred_svmclf_linear))
print(accuracy_score(y_test,y_pred_svmclf_linear))
print(recall_score(y_test,y_pred_svmclf_linear))
print(f1_score(y_test,y_pred_svmclf_linear))
print(precision_score(y_test,y_pred_svmclf_linear))

#Poly
svmclf_linear=SVC(kernel='poly')
svmclf_linear.fit(x_train,y_train)
y_pred_svmclf_poly=svmclf_linear.predict(x_test)
print(confusion_matrix(y_test,y_pred_svmclf_poly))
print(accuracy_score(y_test,y_pred_svmclf_poly))
print(recall_score(y_test,y_pred_svmclf_poly))
print(f1_score(y_test,y_pred_svmclf_poly))
print(precision_score(y_test,y_pred_svmclf_poly))

#rbf
svmclf_linear=SVC(kernel='rbf')
svmclf_linear.fit(x_train,y_train)
y_pred_svmclf_rbf=svmclf_linear.predict(x_test)
print(confusion_matrix(y_test,y_pred_svmclf_rbf))
print(accuracy_score(y_test,y_pred_svmclf_rbf))
print(recall_score(y_test,y_pred_svmclf_rbf))
print(f1_score(y_test,y_pred_svmclf_rbf))
print(precision_score(y_test,y_pred_svmclf_rbf))

#linear_scaled
svmclf_linear_scaled=SVC(kernel='linear')
svmclf_linear_scaled.fit(x_train_scaled,y_train_scaled)
y_pred_svmclf_linear=svmclf_linear_scaled.predict(x_test_scaled)
print(confusion_matrix(y_test_scaled,y_pred_svmclf_linear))
print(accuracy_score(y_test_scaled,y_pred_svmclf_linear))
print(recall_score(y_test_scaled,y_pred_svmclf_linear))
print(f1_score(y_test_scaled,y_pred_svmclf_linear))
print(precision_score(y_test_scaled,y_pred_svmclf_linear))

#Poly_scaled
svmclf_poly_scaled=SVC(kernel='poly')
svmclf_poly_scaled.fit(x_train_scaled,y_train_scaled)
y_pred_svmclf_poly=svmclf_poly_scaled.predict(x_test_scaled)
print(confusion_matrix(y_test_scaled,y_pred_svmclf_poly))
print(accuracy_score(y_test_scaled,y_pred_svmclf_poly))
print(recall_score(y_test_scaled,y_pred_svmclf_poly))
print(f1_score(y_test_scaled,y_pred_svmclf_poly))
print(precision_score(y_test_scaled,y_pred_svmclf_poly))

#rbf_scaled
svmclf_rbf_scaled=SVC(kernel='rbf')
svmclf_rbf_scaled.fit(x_train_scaled,y_train_scaled)
y_pred_svmclf_rbf_scaled=svmclf_rbf_scaled.predict(x_test_scaled)
print(confusion_matrix(y_test_scaled,y_pred_svmclf_rbf_scaled))
print(accuracy_score(y_test_scaled,y_pred_svmclf_rbf_scaled))
print(recall_score(y_test_scaled,y_pred_svmclf_rbf_scaled))
print(f1_score(y_test_scaled,y_pred_svmclf_rbf_scaled))
print(precision_score(y_test_scaled,y_pred_svmclf_rbf_scaled))

#Decision Trees
from sklearn.tree import DecisionTreeClassifier
dt_clf=DecisionTreeClassifier(criterion='entropy')
dt_clf.fit(x_train,y_train)
y_pred_dt=dt_clf.predict(x_test)
print(confusion_matrix(y_test,y_pred_dt))
print(accuracy_score(y_test,y_pred_dt))
print(recall_score(y_test,y_pred_dt))
print(f1_score(y_test,y_pred_dt))
print(precision_score(y_test,y_pred_dt))

#random forest
from sklearn.ensemble import RandomForestClassifier
rf_clf=RandomForestClassifier()
rf_clf.fit(x_train,y_train)
y_pred_rf=rf_clf.predict(x_test)
print(confusion_matrix(y_test,y_pred_rf))
print(accuracy_score(y_test,y_pred_rf))
print(recall_score(y_test,y_pred_rf))
print(f1_score(y_test,y_pred_rf))
print(precision_score(y_test,y_pred_rf))

